name: quip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.1.6
  flutter_contacts: ^1.1.7+1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/loginpagebg.jpg
    - assets/images/profile_photo.jpg
    - assets/images/appicon1.jpeg
    - assets/images/splashscreen.jpeg
